### ISSUE TITLE
Calibration for Sentinel-1 SLC WV

### ISSUE THREAD

**Issue by Ghada-Em** [lprouss/sent1-L1-utilities#1]
Hi Louis-Philippe,
I am working with the S1- WV mode (SLC- level 1) , I tried to calibrate the data with
LUT tables but the "applySent1Lut.m" does not work. Could you please modify the function to support calibrating the WV images? Appreciate it.

**Comment by lprouss** [comment]
Hi,
I simplified the applySent1Lut function to make it easier to use. It should work with SLC images in all mode (IW, EW, SM and WV). I also added a USAGE file to provide examples on how to use the functions.

Please let me know if this solves your problem.
Cheers!
