### ISSUE TITLE
Regarding the issues of "mergeSent1TopsBursts" and "topsDermming"

### ISSUE THREAD

**Issue by bigleaffrog** [lprouss/sent1-L1-utilities#2]
You are currently debugging the code "mergeSent1TopsBursts" and "topsDermming" in the introduction. Do you have any plans to make these two codes public in the future? I really want to learn your code. 
Looking forward to your reply.

**Comment by lprouss** [comment]
Sorry for the delay. Unfortunately, I no longer work with Sentinel-1 data (nor any SAR data) and I have very little time to maintain or improve the tools in this repository. Plus I don't have access to a MATLAB license anymore. Feel free to examine the code of the functions in the dev branch and test them yourself. If I recall correctly, they should work, or at least be close to working, but they may not be that robust. Let me know if you encounter a major problem, and I will try my best to help you. Cheers!
